before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - apk add maven



build1:
  stage: build
  script:
    - echo "Do your build here"
    - mvn compile

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - mvn test


deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
